# Generated by Django 3.1.7 on 2021-04-04 07:03

from django.db import migrations, models
import songs.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Duration', models.PositiveIntegerField()),
                ('Uploaded_time', models.DateTimeField(blank=True, default=None, null=True, validators=[songs.models.validate_date])),
            ],
        ),
    ]
