# Generated by Django 3.1.7 on 2021-04-04 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='Duration',
            new_name='duration',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='Uploaded_time',
            new_name='uploaded_time',
        ),
    ]
