# Generated by Django 3.1.7 on 2021-04-04 15:02

from django.db import migrations, models
import django_mysql.models
import songs.models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0002_auto_20210404_0707'),
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('auther', models.CharField(max_length=100)),
                ('narrator', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='In Seconds')),
                ('uploaded_time', models.DateTimeField(blank=True, default=None, null=True, validators=[songs.models.validate_date])),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='In Seconds')),
                ('uploaded_time', models.DateTimeField(blank=True, default=None, null=True, validators=[songs.models.validate_date])),
                ('host', models.CharField(max_length=100)),
                ('participants', django_mysql.models.ListCharField(models.CharField(max_length=100), max_length=1010, size=10)),
            ],
        ),
        migrations.CreateModel(
            name='Songs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('duration', models.PositiveIntegerField(help_text='In Seconds')),
                ('uploaded_time', models.DateTimeField(blank=True, default=None, null=True, validators=[songs.models.validate_date])),
            ],
        ),
        migrations.DeleteModel(
            name='song',
        ),
    ]
