# Generated by Django 3.1.7 on 2021-04-04 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_auto_20210404_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiobook',
            old_name='auther',
            new_name='author',
        ),
    ]
