# Generated by Django 3.1.7 on 2021-04-04 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_auto_20210404_1510'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Audiobooks',
            new_name='Audiobook',
        ),
        migrations.RenameModel(
            old_name='Podcasts',
            new_name='Podcast',
        ),
        migrations.RenameModel(
            old_name='Songs',
            new_name='Song',
        ),
    ]
